server:
  port: 8084

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-rate-limited
              uri: http://localhost:8081
              order: -1
              predicates:
                - Path=/auth/login,/auth/register
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@ipKeyResolver}"
                    redis-rate-limiter.replenishRate: 1
                    redis-rate-limiter.burstCapacity: 5
                    redis-rate-limiter.requestedTokens: 1
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**

            - id: monitor-service
              uri: http://localhost:8082
              predicates:
                - Path=/monitors/**

            - id: incident-service
              uri: http://localhost:8083
              predicates:
                - Path=/incidents/**

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: file:./.secrets/jwt/public.pem

management:
  endpoint:
    health:
      show-details: always
      show-components: always