server:
  port: 8082

spring:
  application:
    name: monitor-service

  cloud:
    openfeign:
      client:
        config:
          auth-service:
            url: ${AUTH_SERVICE_URL:http://localhost:8081}

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: file:./.secrets/jwt/public.pem

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: monitor-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

  datasource:
    url: jdbc:postgresql://localhost:5432/monitor_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

app:
  kafka:
    topics:
      check-results: ${KAFKA_TOPIC_CHECK_RESULTS:monitor.check-results}
      endpoint-status-changed: ${KAFKA_TOPIC_ENDPOINT_STATUS_CHANGED:incident.endpoint-status-changed}
      notification-subscription: ${KAFKA_TOPIC_NOTIFICATION_SUBSCRIPTION:monitor.notification-subscription}
